version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - run: ./gradlew check
      - store-test-results:
          path: build/test-results
      - store-artifacts:
          path: build/reports/tests/acceptanceTest
          prefix: acceptanceTest
      - store-artifacts:
          path: build/reports/detekt/detekt.html
          prefix: staticAnalysis
